### ISSUE TITLE
Possible issue with > when followed by notes without rhythm signs.

### ISSUE THREAD

**Issue by paul-bayleaf** [cdalitz/abctab2ps#3]
Should the following two bars should be rendered the same?  Both start with a dotted whole note, followed by a half note, then two notes without rhythm signs, which therefore should also be half notes.  But the first bar makes the last two notes whole notes.   A bug?   The user manual says ”&gt;” means  ‘the previous note is dotted, the next note halved’ so the first bar should be equivalent to explicitly dotting the first and halving the second note, as in the second bar.

X:1
T:Possible issue when using >
L:1
K:frenchtab
M:3
f1> h ,g ,h | f3/2 h/ ,g ,h |

![gt-issue](https://github.com/user-attachments/assets/e527733f-32a6-4a13-b322-807603c3501c)

abctab2ps version 1.8.25 (Oct 22 2023)
openSUSE 15.6

**Comment by cdalitz** [comment]
The behaviour that you expected was originally implemented in a very early version of abctab2ps, but it turned out that this was inconvenient because it is in contradiction to the abc standard which says that the '>' should only affect the two adjacent note values.

It is thus not a bug, but a feature. Whether this is a good thing, lies in the eye of the beholder though.
